name: testAction
on: push
jobs:
  testJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'
      - name: Install dependencies
        run: |
          go version
          go mod tidy
      - name: Run build
        run: go build ./cmd/run
      - name: Run test
        run: go test -v ./cmd/run